export const jargonMap = {
  'P/E ratio': 'How much investors pay per dollar of company earnings. A higher number means investors expect faster growth.',
  'market cap': 'Total value of all a company shares combined. Large-cap = over $10B, small-cap = under $2B.',
  'yield': 'Income earned from an investment, shown as a percentage of its price.',
  'dividend': 'A portion of company profits paid out to shareholders, usually quarterly.',
  'bear market': 'A period when stock prices fall 20% or more from recent highs. Investors are pessimistic.',
  'bull market': 'A period of rising stock prices. Investors are optimistic about the economy.',
  'volatility': 'How much an asset price swings up and down. High volatility means bigger price swings.',
  'liquidity': 'How easily you can buy or sell an asset without affecting its price.',
  'hedge': 'An investment made to reduce the risk of another investment moving against you.',
  'short selling': 'Borrowing shares to sell them now, hoping to buy them back cheaper later.',
  'options': 'Contracts giving you the right (but not obligation) to buy or sell an asset at a set price.',
  'ETF': 'Exchange-Traded Fund — a basket of stocks/bonds you can buy like a single share.',
  'basis points': 'A unit equal to 0.01%. So 25 basis points = 0.25%. Used to describe interest rate changes.',
  'inflation': 'The rate at which prices for goods and services rise over time, reducing purchasing power.',
  'recession': 'Two consecutive quarters of economic decline. Often means rising unemployment.',
  'Fed': 'The Federal Reserve — the US central bank that sets interest rates and monetary policy.',
  'interest rate': 'The cost of borrowing money, set by central banks. Higher rates slow borrowing and spending.',
  'GDP': 'Gross Domestic Product — the total value of goods and services produced by a country.',
  'EPS': 'Earnings Per Share — a company\'s profit divided by the number of outstanding shares.',
  'IPO': 'Initial Public Offering — when a private company first sells shares to the public.',
}
