import { Link } from 'react-router-dom'

const INK   = '#0b0b0b'
const CREAM = 'var(--paper)'
const BORDER = 'rgba(240,235,224,0.10)'
const UPDATED = 'May 28, 2026'

function Section({ title, children }) {
  return (
    <section style={{ marginBottom: 48 }}>
      <h2 style={{ fontFamily: 'var(--font-mono)', fontSize: 11, letterSpacing: '0.22em', textTransform: 'uppercase', color: 'rgba(240,235,224,0.38)', marginBottom: 16, fontWeight: 500 }}>
        {title}
      </h2>
      <div style={{ fontFamily: 'var(--font-sans)', fontSize: 14, lineHeight: 1.85, color: 'rgba(240,235,224,0.68)', display: 'flex', flexDirection: 'column', gap: 14 }}>
        {children}
      </div>
    </section>
  )
}

function P({ children }) {
  return <p style={{ margin: 0 }}>{children}</p>
}

export default function Disclaimer() {
  return (
    <div style={{ background: INK, minHeight: '100vh', color: CREAM }}>
      <div style={{ position: 'sticky', top: 0, zIndex: 50, borderBottom: `1px solid ${BORDER}`, background: INK, padding: '0 clamp(20px,6vw,80px)' }}>
        <div style={{ maxWidth: 760, margin: '0 auto', height: 56, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
              <path d="M12 2L22 12L12 22L2 12Z" stroke={CREAM} strokeWidth="1.5" strokeLinejoin="round" />
              <path d="M12 6.5L17.5 12L12 17.5L6.5 12Z" stroke={CREAM} strokeWidth="1.5" strokeLinejoin="round" />
            </svg>
            <span style={{ fontFamily: 'var(--font-sans)', fontWeight: 600, color: CREAM, fontSize: 15 }}>Travauxus</span>
          </Link>
          <Link to="/" style={{ fontFamily: 'var(--font-mono)', fontSize: 11, letterSpacing: '0.12em', color: 'rgba(240,235,224,0.36)', textDecoration: 'none' }}>← Back</Link>
        </div>
      </div>

      <div style={{ maxWidth: 760, margin: '0 auto', padding: 'clamp(48px,8vw,96px) clamp(20px,6vw,80px)' }}>
        <div style={{ marginBottom: 64 }}>
          <p style={{ fontFamily: 'var(--font-mono)', fontSize: 11, letterSpacing: '0.22em', textTransform: 'uppercase', color: 'rgba(240,235,224,0.36)', marginBottom: 16 }}>Legal · Disclaimer</p>
          <h1 style={{ fontFamily: 'var(--font-display)', fontVariationSettings: "'wdth' 125, 'wght' 700", fontStretch: '125%', fontWeight: 700, fontSize: 'clamp(32px,5vw,60px)', letterSpacing: '-0.04em', lineHeight: 0.9, color: CREAM, margin: '0 0 24px' }}>
            Disclaimer
          </h1>
          <p style={{ fontFamily: 'var(--font-sans)', fontSize: 13, color: 'rgba(240,235,224,0.36)' }}>Last updated: {UPDATED}</p>
        </div>

        <div style={{ borderTop: `1px solid ${BORDER}`, paddingTop: 48 }}>
          <Section title="Not Financial Advice">
            <P>Travauxus is an informational and educational platform only. Nothing on this website, including but not limited to market data, AI-generated summaries, news feeds, watchlists, price alerts, government trade activity, or any other content, constitutes financial, investment, legal, or tax advice.</P>
            <P>The information provided is for general informational purposes only and should not be relied upon as the basis for any investment decision.</P>
          </Section>

          <Section title="No Recommendation">
            <P>Any mention of specific securities, cryptocurrencies, commodities, or financial instruments on Travauxus does not constitute a recommendation to buy, sell, or hold those instruments. Past performance is not indicative of future results.</P>
          </Section>

          <Section title="Data Accuracy">
            <P>Market data, prices, and financial information displayed on Travauxus are sourced from third-party providers and may be delayed, incomplete, or inaccurate. We make no warranties regarding the accuracy, completeness, or timeliness of any data displayed on this platform.</P>
            <P>Always verify information independently through official sources and your broker before making any financial decision.</P>
          </Section>

          <Section title="AI-Generated Content">
            <P>Some content on Travauxus is generated by artificial intelligence models. AI-generated summaries, analysis, and insights may contain errors, omissions, or outdated information. They should not be treated as professional financial analysis.</P>
          </Section>

          <Section title="Paper Trading">
            <P>The paper trading feature on Travauxus uses simulated virtual currency. Results achieved in paper trading do not reflect actual market conditions and are not indicative of results you would achieve with real money. Simulated trading does not account for real-world factors such as liquidity constraints, slippage, and brokerage commissions.</P>
          </Section>

          <Section title="Government Trade Data">
            <P>Government official trading data displayed on Travauxus is sourced from public disclosures. This data may be subject to reporting delays mandated by law. Travauxus does not endorse or recommend replicating any official's trading activity.</P>
          </Section>

          <Section title="Risk Warning">
            <P>Investing in financial markets involves significant risk, including the possible loss of principal. You should only invest money you can afford to lose. Seek independent advice from a qualified financial adviser before making any investment decisions.</P>
          </Section>

          <Section title="Limitation of Liability">
            <P>To the maximum extent permitted by applicable law, Travauxus and its operators accept no liability for any loss or damage, including without limitation any loss of profit, which may arise directly or indirectly from use of or reliance on information provided on this platform.</P>
          </Section>

          <Section title="Contact">
            <P>Questions?{' '}
              <a href="mailto:poperwagger@gmail.com" style={{ color: CREAM, textDecoration: 'underline', textUnderlineOffset: 3 }}>poperwagger@gmail.com</a>
            </P>
          </Section>
        </div>

        <div style={{ borderTop: `1px solid ${BORDER}`, marginTop: 64, paddingTop: 32, display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, letterSpacing: '0.18em', color: 'rgba(240,235,224,0.22)' }}>© {new Date().getFullYear()} TRAVAUXUS</span>
          <div style={{ display: 'flex', gap: 24 }}>
            <Link to="/privacy" style={{ fontFamily: 'var(--font-mono)', fontSize: 10, letterSpacing: '0.18em', color: 'rgba(240,235,224,0.22)', textDecoration: 'none' }}>PRIVACY</Link>
            <Link to="/terms" style={{ fontFamily: 'var(--font-mono)', fontSize: 10, letterSpacing: '0.18em', color: 'rgba(240,235,224,0.22)', textDecoration: 'none' }}>TERMS</Link>
          </div>
        </div>
      </div>
    </div>
  )
}
